### ISSUE TITLE
How to show in template list of all activities?

### ISSUE THREAD

**Issue by nurzhannogerbek** [pennersr/django-actistream#4]
Hello! I am interested in your project! Its not issue its just question. Your docs very clear but I am little bit comfused. Can you help me pls.

I have model `Task`. Users can add comments to `Task` objects. I want to show in template list of last 10 activity which was in Task modal. Its seems like its possible to create with your app.

1) I create `activities.py` file with`CommentPosted` class as you said in docs.
2) I have `task_comment_add` function where comments added to tasks.

**views.py:**
```
def task_comment_add(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    ***
    task.comments.add(comment)
    activity = CommentPosted.create(
       target=task,
       actor=request.user,
       action_object=comment,
    )
```

I am little bit comfused after this step. I mean where then I need to use `activity` variable? How can I take list of last activities?

**Comment by pennersr** [comment]
You probably have a task detail view somewhere, that creates a context dictionary to be handed over to the template. This is where you typically fetch the list of activities. For this purpose, the Activity model has a few helper methods, one being `Activity.objects.for_target(task)`.  This will give you a list of activities for that specific task. 

There are also some template tags available to help you out. Suppose you hand over the acitivites resulting from the method above to the context as `activities`, then you could do something like this:

```
{% renderable_activities activities as renderable_activities %}
{% for activity in renderable_activities %}
{% render_activity activity %}
{% endfor %}
```

Note that the activity resulting from your `CommentPosted.create()` can in turn be used to send out a notice to particular users: `Notice.objects.send(activity, [task.user])`

**Comment by pennersr** [comment]
(closing this ticket -- there is nothing to fix in actistream)

**Comment by nurzhannogerbek** [comment]
@pennersr Thank you very much for your answer! I undertand how to show activities for separate task in `task_detail` template. But I need other thing. In my case I have template where I show list of all tasks. At the top of that page I want to show general information about last 10 activities in all tasks? Last activity which was in Task modal much be at the the top of the list (order_by time of activity). What can you advice me in this case?

Here is example:
```
1. User A add comment to Task A.
2. User B add comment to Task C.
3. User B add comment to Task V.
```

I steal have one question as I understand this line `CommentPosted.create(***)` add activity to database. I am right? Is it possible to track other activities like `create/edit` of objects. Something like: `User A edit Task A`?

**Comment by nurzhannogerbek** [comment]
When I tried to put `CommentPosted.create(***)` to my `task_comment_add` function it riase error: `OverflowError: int too big to convert` in `action_object=comment` line. Do you have any ideas why it happens?

**views.py**:
```
def task_comment_add(request, task_id):
    task= get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.save()
            task.comments.add(comment)

            CommentPosted.create(
                target=user_characteristic,
                actor=request.user,
                action_object=comment,
            )
            ******
```

**ERROR:**
```
Traceback (most recent call last):
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Nurzhan\PycharmProjects\RMS\project\views.py", line 605, in task_comment_add
    action_object=comment,
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\actistream\types.py", line 84, in create
    activity.save()
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\models\sql\compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Nurzhan\AppData\Local\Programs\Python\Python35\lib\site-packages\sql_server\pyodbc\base.py", line 539, in execute
    return self.cursor.execute(sql, params)
OverflowError: int too big to convert
```

**Comment by pennersr** [comment]
If you want to list the last 10 activities across all tasks, then you can simply filter on Activity, like so:

        ct = ContentType.objects.get_for_model(Task)
        activities = Activity.objects.filter(target_ct=ct).order_by(-'created_at')[:10]

With respect to the int too big -- I am wondering, what is the `pk` of that comment?  If it is beyond 0 to 2147483647 then indeed there may be an issue (actistream is currently using a PositiveIntegerField).

"Is it possible to track other activities like..."

Sure, feel free to create as many activity types as you like...

**Comment by nurzhannogerbek** [comment]
@pennersr Thank you very much for your answer! =) Now I understand how to show list of last activities for all tasks.

Here below you can see my models with primary key fields. I steal dont know how to fix my last problem: `OverflowError: int too big to convert`.  For example my last test comment's id to task object was supposed to be 14. So as you see its between 0 and 2147483647. I am little bit comfused. What can you advice to me? Change field type of comment `pk` to `PositiveIntegerField`?!

**models.py:**
```
class Task(models.Model):
    code = models.UUIDField(_('Code'), primary_key=True, default=uuid.uuid4, editable=False)
    comments = models.ManyToManyField("Comment")
    ******

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    *****
```

**Comment by pennersr** [comment]
It's not the comment ID that is the problem, the Task ID is. You're using a UUID field as primary key... unfortunately, actistream only supports regular AutoField at this time.. So the easiest way to get things going is to drop primary_key from the code field above. Then, things will work...
